import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'

const files = {
  webpEncWasm: 'node_modules/@jsquash/webp/codec/enc/webp_enc_simd.wasm',
  jpegDecWasm: 'node_modules/@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm',
  pngDecWasm: 'node_modules/@jsquash/png/codec/pkg/squoosh_png_bg.wasm',
}

let out = '// generated by scripts/gen-wasm.mjs, do not edit\n'
for (const [name, path] of Object.entries(files)) {
  out += `export const ${name} = '${readFileSync(path).toString('base64')}'\n`
}

const target = 'server/utils/wasm-binary.ts'
mkdirSync(dirname(target), { recursive: true })
writeFileSync(target, out)
console.log(`[gen] wrote ${target} (${(out.length / 1024).toFixed(0)} KB)`)
